### ISSUE TITLE
Command 'replit clone' doesn't work with my public repl: UnicodeEncodeError

### ISSUE THREAD

**Issue by proxdxd03** [ReplDepot/replit-cli#16]
I tried cloning my public repl to my local machine (using Windows).
This is my command line output:
```
replit clone RSCompetition/RSCompetitionBot
Client instantiated






state: 1608

id: 35
state: 1608

Channel opened
REFRESHING FILE/DIR FROM SERVER - commandmodules.js
REFRESHING FILE/DIR FROM SERVER - commands.js
REFRESHING FILE/DIR FROM SERVER - ids.js
REFRESHING FILE/DIR FROM SERVER - index.js
REFRESHING FILE/DIR FROM SERVER - log.js
REFRESHING FILE/DIR FROM SERVER - package-lock.json
REFRESHING FILE/DIR FROM SERVER - package.json
REFRESHING FILE/DIR FROM SERVER - db/mongodb.js
REFRESHING FILE/DIR FROM SERVER - node_modules/asynckit/LICENSE
REFRESHING FILE/DIR FROM SERVER - node_modules/asynckit/README.md
REFRESHING FILE/DIR FROM SERVER - node_modules/asynckit/bench.js
REFRESHING FILE/DIR FROM SERVER - node_modules/asynckit/index.js
REFRESHING FILE/DIR FROM SERVER - node_modules/asynckit/package.json
REFRESHING FILE/DIR FROM SERVER - node_modules/asynckit/parallel.js
REFRESHING FILE/DIR FROM SERVER - node_modules/asynckit/serial.js
REFRESHING FILE/DIR FROM SERVER - node_modules/asynckit/serialOrdered.js
REFRESHING FILE/DIR FROM SERVER - node_modules/asynckit/stream.js
REFRESHING FILE/DIR FROM SERVER - node_modules/base64-js/LICENSE
REFRESHING FILE/DIR FROM SERVER - node_modules/base64-js/README.md
REFRESHING FILE/DIR FROM SERVER - node_modules/base64-js/base64js.min.js
REFRESHING FILE/DIR FROM SERVER - node_modules/base64-js/index.d.ts
REFRESHING FILE/DIR FROM SERVER - node_modules/base64-js/index.js
REFRESHING FILE/DIR FROM SERVER - node_modules/base64-js/package.json
REFRESHING FILE/DIR FROM SERVER - node_modules/bson/LICENSE.md
REFRESHING FILE/DIR FROM SERVER - node_modules/bson/README.md
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\replit.exe\__main__.py", line 4, in <module>
  File "C:\Python310\lib\site-packages\repl_cli\main.py", line 758, in <module>
    app()
  File "C:\Python310\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Python310\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python310\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Python310\lib\site-packages\click\core.py", line 1259, in invoke
  File "C:\Python310\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python310\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Python310\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Python310\lib\site-packages\repl_cli\main.py", line 174, in clone
    downloadRepl(user, replname)
  File "C:\Python310\lib\site-packages\repl_cli\main.py", line 146, in downloadRepl
    f.write(content)
  File "C:\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 4921-4922: character maps to <undefined>
```

**Comment by CoolCoderSJ** [comment]
It seems the repl has a corrupt file somewhere in node modules, but I'm not sure how to fix it because that shouldn't happen in the first place. You also may want to not clone all of node modules, because that would take way too much time. Try deleting the folder through the shell and then cloning it. This won't affect your repl, you can just run npm install to get it back.

**Comment by proxdxd03** [comment]
I definitely don't want to delete the node_modules folder because I changed one class name in a dependency to avoid errors with importing / compiling from my Typescript codebase. How can I clone a certain folder of my repl?

**Comment by proxdxd03** [comment]
I actually only want to sync my Javascript compiled code and nothing else...

**Comment by proxdxd03** [comment]
Can you please tell me how I can sync a certain folder of my repl and leave the other stuff untouched?

**Comment by CoolCoderSJ** [comment]
Hi sorry I skipped over this for some reason,
Gimme a few days and I'll add it as a feature

**Comment by CoolCoderSJ** [comment]
added

To upgrade, 
```bash
pip install repl_cli --upgrade
```

Clone or pull a specific directory
```bash
replit clone username/replname --dir=myDir
```
```bash
replit pull --dir=myDIr
```

To clone or pull a specific file-
```bash
replit clone username/replname --file=a_file.txt
```
```bash
replit pull --file=a_file.txt
```

**Comment by proxdxd03** [comment]
Thanks! I'll try in a minute.

**Comment by proxdxd03** [comment]
@CoolCoderSJ 
I just reinstalled and created a new directory called `test` in my repl. In it I created a file called `lol`. The content of it was `agnfhjkhggvf`. Cloning it didn't throw an exception but the cloned file contains `cat:` instead of `agnfhjkhggvf`.

**Comment by proxdxd03** [comment]
Oh, and trying to pull a specific directory (`test` from my repl from my previous post) gets stuck forever.

**Comment by CoolCoderSJ** [comment]
That definitely shouldn't be happening and worked smoothly when I tested. Could you share a repl I could investigate?

Also the freezing is known, the temporary fix is to go to your repl, click the shell tab, run `kill 1` and try again.

**Comment by proxdxd03** [comment]
My repl is [](https://replit.com/@RSCompetition/RSCompetitionBot#index.js), it's compiled from Typescript. I'll try doing the freeze fix and then pulling again in a minute.

**Comment by CoolCoderSJ** [comment]
Erm could I have a url please

Also no, it's something to do with the client hanging sometimes and won't open a channel inside of a client properly
I thought I fixed it but I guess not

**Comment by proxdxd03** [comment]
Oh oops, the URL embed didn't work... My repl is [here](https://replit.com/@RSCompetition/RSCompetitionBot#index.js). Also the pull worked now, but the file now contains `cat: lol: No such file or directory`.

**Comment by CoolCoderSJ** [comment]
I encountered these bugs during preliminary testing while I was working on #14, but to my knowledge they went away...
I'll take a look

**Comment by CoolCoderSJ** [comment]
Fixed.

There seems to have been a fundamental flaw in the logic, so I don't know how it worked at all during my tests.

**Comment by proxdxd03** [comment]
I had another problem, which also broke the functionality of my repl, but I don't know if it was connected to this one, so I made a new ticket #17 . Please consider checking it.
