### ISSUE TITLE
Repl file is not changable and at incomplete state.

### ISSUE THREAD

**Issue by proxdxd03** [ReplDepot/replit-cli#17]
After I tried using a shell script to upload my folder (using a single-folder replit-cli setup), my repl contains an index.js file that automatically gets reset when being changed and thus crashes my program. My shell script is
```
replit login --sid [SID]
echo Login done!
tsc ./ts/index.ts --outDir ./out
echo Compile done!
cd ./RSCompetitionBot/
replit run RSCompetition/RSCompetitionBot --stop
echo Stop done!
replit push
echo Push done!
replit run RSCompetition/RSCompetitionBot
echo Rerun done!
cd ./../
echo Done!
```
My upload script froze at stopping the repl.

**Comment by CoolCoderSJ** [comment]
I dont really know how to fix the command freezing at the repl stop, because it seems to work for me.
I'll look into the pushing.

https://user-images.githubusercontent.com/53063247/157756812-d0a1841d-b84d-4e3b-8bc0-0bf134a3e9b4.mp4

**Comment by proxdxd03** [comment]
I think I figured sth out. I'm probably responsible for the error myself.

**Comment by proxdxd03** [comment]
I'll tell you after I analyzed more detailedly.

**Comment by proxdxd03** [comment]
So I didn't compile my whole project and compiled it into the wrong folder. But still, now I found something that is probably not intended. When trying to set it up, my subfolder changed into a file containing `cat: out/db: Is a directory`.

**Comment by proxdxd03** [comment]
K, so I fixed the problem with the db folder by just creating a db folder in my out directory. Now I'm getting `UnicodeDecodeError` again. Could that be caused by a windows emoji (👍)? I'm doing a Discord bot and this is the easiest way to check an emoji type, but I think I could change that if it would fix the error.

**Comment by proxdxd03** [comment]
Also, it might still get stuck by the run command, if the `UnicodeDecodeError` isn't crashing the program.

**Comment by proxdxd03** [comment]
When removing all files but `commandmodules.js`, `ids.js` and `index.js` (leaving the `db` folder there), I get a `PermissionError: [Errno 13] Permission denied: 'out/db'`.
Shell script is currently
```
replit login --sid [SID]
echo Login done!
# tsc ./ts/index.ts --outDir ./RSCompetitionBot/out/
# tsc ./ts/commands.ts --outDir ./RSCompetitionBot/out/
# tsc ./ts/commandmodules.ts --outDir ./RSCompetitionBot/out/
# tsc ./ts/db/mongodb.ts --outDir ./RSCompetitionBot/out/db/
# tsc ./ts/ids.ts --outDir ./RSCompetitionBot/out/
# tsc ./ts/log.ts --outDir ./RSCompetitionBot/out/
# tsc ./ts/util.ts --outDir ./RSCompetitionBot/out/
echo Compile done!
cd ./RSCompetitionBot/
# replit run RSCompetition/RSCompetitionBot --stop
echo Stop done!
replit push
echo Push done!
replit run RSCompetition/RSCompetitionBot --restart
echo Rerun done!
cd ./../
echo Done!
```

**Comment by proxdxd03** [comment]
Oh, and when I try the `replit run` command in my terminal, I get ```raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.``` after a while. I hope this information will help you at solving my problem. For now, my repl isn't frozen anymore, so the problem isn't this problematic. Thank you for your patience!

**Comment by proxdxd03** [comment]
I just found out another file is frozen now.

**Comment by CoolCoderSJ** [comment]
So pushing errors, empty directory pulling errors, or both?
Which one should I look into

**Comment by proxdxd03** [comment]
I get:
- `UnicodeDecodeError` when using `replit push`
- `WebSocketConnectionClosedException` when using `replit run`
- `PermissionError` when using `replit push` while I removed some of my files
- ocassionally frozen files in repl.it (I can type in them, but they are reverted after a few seconds)

**Comment by CoolCoderSJ** [comment]
I'm not sure what's causing the UnicodeDecode.

I'm able to read a unicode file properly
![image](https://user-images.githubusercontent.com/53063247/158041348-ae8c5654-5d02-4b89-b0c2-b62cfb9c2e10.png)

Yes, it doesn't render properly in the terminal but that's a Windows issue. The actual code isn't erroring.
I'll try looking into it more.

**Comment by CoolCoderSJ** [comment]
I'm really not sure what could be causing your replit run issue.

https://user-images.githubusercontent.com/53063247/158045169-ec3cc2ea-ffbc-4e21-878f-b87584621949.mp4


Usually, when you encounter a Client Closed Exception, it's usually best to try and run kill 1 in your repl then try again, or just try the command again.

**Comment by proxdxd03** [comment]
So, it (I think I sent you the stacktrace earlier) mentioned a charmap at the `UnicodeDecodeError`; do you think the error may be fixable by manipulating that map? And can you please send me an example file to test if I can upload your code without a `UnicodeDecodeError`? Also, in which cases does repl.it revert online file changes?

**Comment by CoolCoderSJ** [comment]
Erm you didn't, you only mentioned using emojis. I'll try testing with your repl directly today.

As for the 2 file push issues, the whole file pushing needs to be redone. Shouldn't take too long.

**Comment by CoolCoderSJ** [comment]
I believe I've fixed the last two issues, the server-side companion that helps with pulling has been refreshed and now works smoother.

**Comment by CoolCoderSJ** [comment]
Using your repl I do see the UnicodeDecode error even while pulling, investigation time.

**Comment by CoolCoderSJ** [comment]
The emojis do seem to be the problem because when I removed them it worked. I wonder why, considering my mini test with the emoji reading worked...

**Comment by CoolCoderSJ** [comment]
I've sort of found the issue and it seems like I can't think of a fix. I'll try to see what I can do.

**Comment by proxdxd03** [comment]
I'll try to find a fix for the emoji, there must be a way of Discord to let me access it without the unicode emoji. The files are now unfrozen for me, I'll test the rest in a minute.

**Comment by proxdxd03** [comment]
So basically everything works now, except for the restarting. That still gets stuck, even after entering `kill 1`. I removed the line to stop the repl since restart should do everything I need.

**Comment by CoolCoderSJ** [comment]
Commit `ba7d611` should fix it. Technically it does restart the reply because if I log the repl start time, it changes when I run the restart command.

**Comment by proxdxd03** [comment]
So I download said commit, run the restart command once and then switch back to the newest version?

**Comment by proxdxd03** [comment]
Wait, I just noticed it's a new commit. Didn't see this.

**Comment by CoolCoderSJ** [comment]
Just update the CLI by doing 
```
pip install repl_cli --upgrade
``` and you should be good to go

**Comment by proxdxd03** [comment]
Does the `run` run as long as the repl runs? Or does it finish when the repl started?

**Comment by CoolCoderSJ** [comment]
The new commit/release (1.2.6)
(Check version with `replit version`
Fixes that so the command finishes as soon as the repl starts up.

**Comment by proxdxd03** [comment]
Hmm, after all it seems to still just not refresh my repl and get stuck. Does having the page open affect how it acts?

**Comment by CoolCoderSJ** [comment]
Not at all. When I tested the commands, I had the windows open side by side.

That's really weird

**Comment by proxdxd03** [comment]
Is there a difference in code between connecting to the repl shell and running `node .` and entering `replit run`? Is it a difference between different languages (You're probably using Python, I'm using Javascript)?

**Comment by CoolCoderSJ** [comment]
Yes
No

Shell commands are silent; They run on a thread not visible on the website. The run commands instruct the Replit API to use the **main** thread, so you can see it on the website too.

**Comment by proxdxd03** [comment]
Ok, so that means it is language independent?

**Comment by CoolCoderSJ** [comment]
No, the language has nothing to do with this
Shell uses a hidden thread to run your commands, the run command uses the main thread so it reflects the changes on the website.

**Comment by CoolCoderSJ** [comment]
Wdym somewhere else

Also wouldn't change anything

**Comment by proxdxd03** [comment]
Put the main script into a folder and then change the `package.json` so that it is still recognized as main script. What happens then if you start using the repl-cli?

**Comment by CoolCoderSJ** [comment]
I'm not sure you're getting the point that your files have nothing to do with this
The way Replit's goval API works is that the exec service, which the `shell` command uses, uses a random thread that isn't reflected on the website. 
The runner service, which the run command uses, uses the main thread. So your changes are reflected on the website.
If you want to run your repl, I suggest you use the actual run command and not the shell command.

**Comment by proxdxd03** [comment]
Ok. But since that doesn't seem to work, I think I won't be able to use your cli. If you find another way how to restart the repl, please tell me, but for now I'll discontinue getting the cli to work for me and continue coding. Thanks for your friendly and fast help anyways!

**Comment by CoolCoderSJ** [comment]
Could you try running the stop command then run command and see if that works

**Comment by proxdxd03** [comment]
Thank you.

**Comment by proxdxd03** [comment]
1.2.6

**Comment by CoolCoderSJ** [comment]
Oh

try running `kill 1` in your repl and try again

**Comment by proxdxd03** [comment]
Still freezing

**Comment by CoolCoderSJ** [comment]
what are your required env variables
I'll test it directly with your repl

**Comment by CoolCoderSJ** [comment]
Update to the latest version (1.2.7) with
```
pip install repl_cli --upgrade
```

**Comment by proxdxd03** [comment]
I'm sorry that I didn't answer yet, I got many things going right now, so I was a bit overstressed. I just randomly checked out our thread again, and it worked after reupdating the repl-cli!

**Comment by proxdxd03** [comment]
Thank you!

**Comment by CoolCoderSJ** [comment]
no worries, have a great day!

**Comment by proxdxd03** [comment]
You too! Thank you for all your help!
